from rose.lib import datasets, util

INVALID_EMOTIONS = [
    emotion for dataset in datasets.datasets.values()
    for emotion in dataset.INVALID_EMOTIONS
]
EXPANDED_EMOTIONS = [*util.EMOTIONS, *INVALID_EMOTIONS]

translation_english = {emotion: emotion for emotion in EXPANDED_EMOTIONS}
translation_spanish = {
    "Aburrimiento": "Boredom",
    "Admiración": "Admiration",
    "Adoración": "Adoration",
    "Alegría": "Joy",
    "Alivio": "Relief",
    "Amor": "Love",
    "Angustia": "Distress",
    "Ansiedad": "Anxiety",
    "Antojo": "Craving",
    "Apreciación Estética": "Aesthetic Appreciation",
    "Asco": "Disgust",
    "Asombro Maravillado": "Awe",
    "Calma": "Calmness",
    "Cansancio": "Tiredness",
    "Concentración": "Concentration",
    "Confusión": "Confusion",
    "Contemplación": "Contemplation",
    "Contentamiento": "Contentment",
    "Culpa": "Guilt",
    "Decepción": "Disappointment",
    "Deseo Sexual": "Sexual Desire",
    "Desprecio": "Contempt",
    "Determinación": "Determination",
    "Diversión": "Amusement",
    "Dolor": "Pain",
    "Dolor Empático": "Empathic Pain",
    "Duda": "Doubt",
    "Enojo": "Anger",
    "Entusiasmo": "Excitement",
    "Envidia": "Envy",
    "Éxtasis": "Ecstasy",
    "Hipnosis": "Entrancement",
    "Interes": "Interest",
    "Miedo": "Fear",
    "Nostalgia": "Nostalgia",
    "Orgullo": "Pride",
    "Pena": "Embarrassment",
    "Realización": "Realization",
    "Romance": "Romance",
    "Satisfacción": "Satisfaction",
    "Simpatía": "Sympathy",
    "Sorpresa (negativa)": "Surprise (negative)",
    "Sorpresa (positiva)": "Surprise (positive)",
    "Terror": "Horror",
    "Torpeza": "Awkwardness",
    "Tristeza": "Sadness",
    "Triunfo": "Triumph",
    "Vergüenza": "Shame",
    "Sin Rostro Visible": "Face Not Visible",
    "No hay voz": "Voice Not Audible",
}
translation_chinese = {
    "钦佩": "Admiration",
    "爱慕": "Adoration",
    "审美鉴赏": "Aesthetic Appreciation",
    "乐趣": "Amusement",
    "气愤": "Anger",
    "焦虑": "Anxiety",
    "敬畏": "Awe",
    "下决心": "Awkwardness",
    "尴尬": "Boredom",
    "无聊": "Calmness",
    "平静": "Concentration",
    "专注": "Contemplation",
    "沉思": "Confusion",
    "困惑": "Contempt",
    "轻蔑": "Contentment",
    "知足": "Craving",
    "渴望": "Determination",
    "失望": "Disappointment",
    "厌恶": "Disgust",
    "苦恼": "Distress",
    "疑虑": "Doubt",
    "狂喜": "Ecstasy",
    "窘迫": "Embarrassment",
    "同理的痛苦": "Empathic Pain",
    "入迷": "Entrancement",
    "羡慕": "Envy",
    "兴奋": "Excitement",
    "害怕": "Fear",
    "内疚": "Guilt",
    "惊恐": "Horror",
    "兴趣": "Interest",
    "欢乐": "Joy",
    "爱": "Love",
    "怀念": "Nostalgia",
    "痛苦": "Pain",
    "自豪": "Pride",
    "领悟": "Realization",
    "解脱": "Relief",
    "浪漫": "Romance",
    "悲伤": "Sadness",
    "满足": "Satisfaction",
    "性欲": "Sexual Desire",
    "羞耻": "Shame",
    "惊讶(正性)": "Surprise (negative)",
    "惊讶(负性)": "Surprise (positive)",
    "同情": "Sympathy",
    "疲惫": "Tiredness",
    "胜利": "Triumph",
}
translation_ethiopian = {
    "አድናቆት": "Admiration",
    "አክብሮት": "Adoration",
    "ውበትማድነቅ": "Aesthetic Appreciation",
    "መደሰት": "Amusement",
    "ንዴት": "Anger",
    "ጭንቀት": "Anxiety",
    "መገረም": "Awe",
    "አለመመቸት": "Awkwardness",
    "አሰልቺ": "Boredom",
    "ጸጥተኛነት": "Calmness",
    "አትኩሮት": "Concentration",
    "ማሰላሰል": "Contemplation",
    "ግራ መጋባት": "Confusion",
    "ንቀት": "Contempt",
    "እርካታ": ["Contentment", "Satisfaction"],
    "አምሮት": "Craving",
    "ቆራጥነት": "Determination",
    "ቅሬታ": "Disappointment",
    "ጸያፍ": "Disgust",
    "የትጨነቀ": "Distress",
    "ጥርጣሬ": "Doubt",
    "ፍንደቃ": "Ecstasy",
    "እፍረት": ["Embarrassment", "Shame"],
    "የሌላውን ህመም እንደራስ ማየት": "Empathic Pain",
    "የህሳብ ጥልቀት መግባት": "Entrancement",
    "ቅናት": "Envy",
    "የደስታ ስሜት": "Excitement",
    "ፍርሃት": "Fear",
    "ጥፋተኝነት": "Guilt",
    "የሚያስፈራ": "Horror",
    "የሚወደድ ነገር": "Interest",
    "ደስታ": "Joy",
    "ፍቅር": "Love",
    "ናፍቆት": "Nostalgia",
    "ህመም": "Pain",
    "ኩራት": "Pride",
    "እውን ማድረግ": "Realization",
    "እፎይታ": "Relief",
    "የፍቅር ስሜት": "Romance",
    "ማዘን": "Sadness",
    "የወሲብ ፍላጎት": "Sexual Desire",
    "አሉታዊ አስገራሚ": "Surprise (negative)",
    "አዎንታዊ አስገራሚ": "Surprise (positive)",
    "የሀዘን ተካፋይ መሆን": "Sympathy",
    "ድካም": "Tiredness",
    "ድል": "Triumph",
}

translation = {
    **translation_ethiopian,
    **translation_chinese,
    **translation_spanish,
    **translation_english,
}
